TMA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('tma_app.urls'))
]

tma_app/urls.py
"""Defines URL patterns for tma"""

from django.urls import path

from . import views

app_name = 'tma_app'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all items.
    path('items/', views.items, name='items'),
    # Page that shows list of purchase requests.
    path('requests/', views.requests, name='requests'),
    # Page for adding a new item.
    path('new_item/', views.new_item, name='new_item'),
    # Page for editing selected item
    path('edit_item/<int:item_id>/', views.edit_item, name='edit_item'),
    # Page for deleting selected item
    path('delete_item/<int:item_id>', views.delete_item, name='delete_item'),
    # Page for denying requests
    path('deny_request/<int:request_id>', views.deny_request, name='deny_request'),
    # Page for approving requests
    path('approve_request/<int:request_id>', views.approve_request, name='approve_request'),
    # Page for ordering items
    path('order_item/<int:item_id>', views.order_item, name='order_item')
]

tma_app/models.py
from django.db import models

class Items(models.Model):
    item_id = models.AutoField(primary_key=True)
    CHOICE_1 = "test1"
    CHOICE_2 = 'test2'
    ITEM_GROUPS = {
        CHOICE_1: "test1",
        CHOICE_2: "test2"
    }
    item_group = models.CharField(
        choices=ITEM_GROUPS,
        default=CHOICE_1
    )
    KILO = "Kilogram"
    MILI = "Miligram"
    UNITS = {
        KILO: "Kilogram",
        MILI: "Miligram"
    }
    unit_of_measurement = models.CharField(
        choices=UNITS,
        default=KILO
    )
    quantity = models.IntegerField()
    price_without_vat = models.IntegerField()
    status = models.CharField(max_length=50)
    storage_location = models.CharField(max_length=50, blank=True, null=True)
    contact_person = models.CharField(blank=True, null=True)
    photo = models.CharField(blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Items'

    def __str__(self):
        """Return string representation of the id"""
        return f"{self.item_id}"
class TmaRequests(models.Model):
    request_id = models.AutoField(primary_key=True)
    employee_name = models.CharField()
    item = models.ForeignKey(Items, on_delete=models.CASCADE, blank=True, null=True)
    KILO = "Kilogram"
    MILI = "Miligram"
    UNITS = {
        KILO: "Kilogram",
        MILI: "Miligram"
    }
    unit_of_measurement = models.CharField(
        choices=UNITS,
        default=KILO
    )
    quantity = models.IntegerField()
    price_without_vat = models.IntegerField()
    comment = models.CharField(blank=True, null=True)
    DENIED = "Denied"
    APPROVED = "Approved"
    NEW = "New"
    ITEM_STATUS = {
        DENIED: "Denied",
        APPROVED: "Approved",
        NEW: "New"
    }
    status = models.CharField(
        choices=ITEM_STATUS,
        default=NEW,
        null=True)

    class Meta:
        verbose_name_plural = 'TmaRequests'

tma_app/forms.py
from django import forms

from .models import Items, TmaRequests


class ItemsForm(forms.ModelForm):
   class Meta:
        model = Items
        fields = ['item_group',
                  'unit_of_measurement',
                  'quantity',
                  'price_without_vat',
                  'status',
                  'storage_location',
                  'contact_person']

class DenyRequestForm(forms.ModelForm):
    class Meta:
        model = TmaRequests
        fields = ['comment',
                  'status']
        exclude = ['status']

class OrderItemForm(forms.ModelForm):
    class Meta:
        model = Items
        fields = ['item_group',
                  'unit_of_measurement',
                  'quantity',
                  'price_without_vat',
                  'status']
        exclude = ['status']

tma_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import Items, TmaRequests
from .forms import ItemsForm, DenyRequestForm, OrderItemForm
from .check_permissions import group_required


item_headers = {'item_id': 'asc',
            'item_group': 'asc',
            'unit_of_measurement': 'asc',
            'quantity': 'asc',
            'price_without_vat': 'asc',
            'status': 'asc',
            'storage_location': 'asc',
            'contact_person': 'asc'}

requests_headers = {'request_id': 'asc',
            'employee_name': 'asc',
            'item_id': 'asc',
            'unit_of_measurement': 'asc',
            'quantity': 'asc',
            'price_without_vat': 'asc',
            'comment': 'asc',
            'status': 'asc'}

def index(request):
    """The home page for tma"""
    return render(request, 'tma_app/index.html')

@login_required
def items(request):
    """Show all items"""
    sort = request.GET.get('sort')
    items = Items.objects.all()
    if sort is not None:
        items = items.order_by(sort)
        if item_headers[sort] == "des":
            items = items.reverse()
            item_headers[sort] = "asc"
        else:
            item_headers[sort] = "des"

    context = {'items': items}
    return render(request, 'tma_app/items.html', context)

@login_required
def requests(request):
    """Show all requests"""
    sort = request.GET.get('sort')
    requests = TmaRequests.objects.all()
    if sort is not None:
        requests = requests.order_by(sort)
        if requests_headers[sort] == "des":
            requests = requests.reverse()
            requests_headers[sort] = "asc"
        else:
            requests_headers[sort] = "des"

    context = {'requests': requests}
    return render(request, 'tma_app/requests.html', context)

@login_required
@group_required("Coordinator", "Administrator")
def new_item(request):
    """Add a new item"""
    if request.method != 'POST':
        # No data submitted; create a blank form
        form = ItemsForm()
    else:
        # POST data submitted; process data
        form = ItemsForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('tma_app:items')

    # display a blank or invalid form.
    context = {'form': form}
    return render(request, 'tma_app/new_item.html', context)

@login_required
@group_required("Coordinator", "Administrator")
def edit_item(request, item_id):
    """Edit existing item"""
    item = Items.objects.get(item_id=item_id)

    if request.method != 'POST':
        # Initial request; pre fill form with the current entry
        form = ItemsForm(instance=item)
    else:
        # POST data submitted; process data
        form = ItemsForm(instance=item, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('tma_app:items')

    context = {'item': item, 'form': form}
    return render(request, 'tma_app/edit_item.html', context)

@login_required
@group_required("Coordinator", "Administrator")
def delete_item(request, item_id):
    """Delete chosen item"""
    item = Items.objects.get(item_id=item_id)

    if request.method == 'POST':
        item.delete()
        return redirect('tma_app:items')

    context = {'item': item}
    return render(request, 'tma_app/delete_item.html', context)

@login_required
@group_required("Coordinator", "Administrator")
def deny_request(request, request_id):
    """Deny the request and set it's status to 'denied' - also ask for comment if possible"""
    item = TmaRequests.objects.get(request_id=request_id)

    if request.method != 'POST':
        # Initial request; pre fill form with the current entry
        form = DenyRequestForm(instance=item)
    else:
        # POST data submitted; process data
        form = DenyRequestForm(instance=item, data=request.POST)
        if form.is_valid():
            form.instance.status = "Denied"
            form.save()
            return redirect('tma_app:requests')

    context = {'item': item, 'form': form}
    return render(request, 'tma_app/deny_request.html', context)

@login_required
@group_required("Coordinator", "Administrator")
def approve_request(request, request_id):
    """Aprove chosen request"""
    item = TmaRequests.objects.get(request_id=request_id)
    item2 = Items.objects.get(item_id=item.item_id)

    if request.method == 'POST':
        item2.quantity -= item.quantity
        item.status = "Approved"
        item.save()
        item2.save()
        return redirect('tma_app:requests')


    context = {'item': item}
    return render(request, 'tma_app/approve_request.html', context)

@login_required
@group_required("Coordinator", "Administrator", "Employee")
def order_item(request, item_id):
    """Order an item"""
    item = Items.objects.get(item_id=item_id)

    if request.method != 'POST':
        # No data submitted, create pre filled form
        form = OrderItemForm(instance=item)
    else:
        # Post data submitted; process data
        form = OrderItemForm(data=request.POST)
        if form.is_valid():
            form.instance.status = "New"
            form.save()
            return redirect('tma_app:items')

    context = {'item': item, 'form': form}
    return render(request, 'tma_app/order_item.html', context)

templates/tma_app/approve_request.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Approve Request</title>
</head>
<body>
{% extends 'tma_app/base.html' %}
{% block content %}
	<form action="{% url 'tma_app:approve_request' item.request_id %}" method="post">
        {% csrf_token %}
        <button name="submit">Approve</button>
    </form>
{% endblock %}
</body>
</html>

templates/tma_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>base</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css'%}"/>
</head>
<body>
<p class="base_p">
    {% if user.is_authenticated %}
    	You are currently logged in as:  {{ user.username }} ||
        {% else %}
        <a href="{% url 'accounts:login' %}">Log in</a>
    {% endif %}
    <a href="{% url 'tma_app:index' %}">Main site</a>
    <a href="{% url 'tma_app:items' %}">Items</a>
    <a href="{% url 'tma_app:requests' %}">Requests</a>
</p>
{% block content %}{% endblock %}
    {% if user.is_authenticated %}
        <hr />
        <form class="logout" action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button name="submit">Log out</button>
        </form>
    {% endif %}
</body>
</html>

templates/tma_app/delete_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete item</title>
</head>
<body>
{% extends 'tma_app/base.html' %}
{% block content %}
	<form action="{% url 'tma_app:delete_item' item.item_id %}" method="post">
        {% csrf_token %}
        <button name="submit">Delete</button>
    </form>
{% endblock %}
</body>
</html>

templates/tma_app/deny_request.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Deny Request</title>
</head>
<body>
{% extends 'tma_app/base.html' %}
{% block content %}
    <form action="{% url 'tma_app:deny_request' item.request_id %}" method="post">
        {% csrf_token %}
        {{ form.as_div }}
        <button name="submit">Deny</button>
    </form>
{% endblock %}
</body>
</html>

templates/tma_app/edit_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Item</title>
</head>
<body>
{% extends 'tma_app/base.html' %}
{% block content %}
	<p>{{ item_id }}</p>
    <form action="{% url 'tma_app:edit_item' item.item_id %}" method="post">
        {% csrf_token %}
        {{ form.as_div }}
        <button name="submit">Save changes</button>
    </form>
{% endblock %}
</body>
</html>

templates/tma_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TMA</title>
</head>
<body>
{% extends 'tma_app/base.html' %}
{% block content %}
	<p>TMA - This site should display which user is logged in if logged, and if not it
    should allow user to log in</p>
{% endblock %}
</body>
</html>

templates/tma_app/items.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'tma_app/base.html' %}
    <meta charset="UTF-8">
    <title>Items</title>
</head>
<body>
{% block content %}
        <h1><a href="{% url "tma_app:new_item" %}">Add new item</a></h1>
    <table>
    <tr>
        <th><a href="?sort=item_id">Item ID</a></th>
        <th><a href="?sort=item_group">Item Group</a></th>
        <th><a href="?sort=unit_of_measurement">Unit of measurement</a></th>
        <th><a href="?sort=quantity">Quantity</a></th>
        <th><a href="?sort=price_without_vat">Price without VAT</a></th>
        <th><a href="?sort=status">Status</a></th>
        <th><a href="?sort=storage_location">Storage location</a></th>
        <th><a href="?sort=contact_person">Contact person</a></th>
        <th>Edit</th>
        <th>Remove</th>
        <th>Order</th>
    </tr>
    {% for object in items %}
        <tr>
            <td>{{ object.item_id }}</td>
            <td>{{ object.item_group }}</td>
            <td>{{ object.unit_of_measurement }}</td>
            <td>{{ object.quantity }}</td>
            <td>{{ object.price_without_vat }}</td>
            <td>{{ object.status }}</td>
            <td>{{ object.storage_location }}</td>
            <td>{{ object.contact_person }}</td>
            <td><a href="{% url 'tma_app:edit_item' object.item_id %}">Click to edit</a></td>
            <td><a href="{% url 'tma_app:delete_item' object.item_id %}">Click to remove</a></td>
            <td><a href="{% url 'tma_app:order_item' object.item_id %}">Click to order</a></td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}
</body>
</html>

templates/tma_app/lack_permissions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Access denied</title>
</head>
<body>
{% extends 'tma_app/base.html' %}
{% block content %}
	<h1>You lack permissions to do that action</h1>
{% endblock %}
</body>
</html>

templates/tma_app/new_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New item</title>
</head>
<body>
{% extends 'tma_app/base.html' %}
{% block content %}
	<form action="{% url 'tma_app:new_item' %}" method="post">
        {% csrf_token %}
        {{ form.as_div }}
        <button name="submit">Add new item</button>
    </form>
{% endblock %}
</body>
</html>

templates/tma_app/order_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order Item</title>
</head>
<body>
{% extends 'tma_app/base.html' %}
{% block content %}
    <form action="{% url 'tma_app:order_item' item.item_id %}" method="post">
        {% csrf_token %}
        {{ form.as_div }}
    <button name="submit">Submit</button><a class="button" href="{% url 'tma_app:items' %}">Cancel</a>
    </form>
{% endblock %}
</body>
</html>

templates/tma_app/requests.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'tma_app/base.html' %}
    <meta charset="UTF-8">
    <title>Requests</title>
</head>
<body>
{% block content %}
    <table>
    <tr>
        <th><a href="?sort=request_id">Request ID</a></th>
        <th><a href="?sort=employee_name">Employee name</a></th>
        <th><a href="?sort=item_id">Item ID</a></th>
        <th><a href="?sort=unit_of_measurement">Unit of measurement</a></th>
        <th><a href="?sort=quantity">Quantity</a></th>
        <th><a href="?sort=price_without_vat">Price without VAT</a></th>
        <th><a href="?sort=comment">comment</a></th>
        <th><a href="?sort=status">status</a></th>
        <th>Confirm Request</th>
        <th>Deny Request</th>
    </tr>
    {% for object in requests %}
        <tr>
            <td>{{ object.request_id }}</td>
            <td>{{ object.employee_name }}</td>
            <td>{{ object.item }}</td>
            <td>{{ object.unit_of_measurement }}</td>
            <td>{{ object.quantity }}</td>
            <td>{{ object.price_without_vat }}</td>
            <td>{{ object.comment }}</td>
            <td>{{ object.status }}</td>
            {% if object.quantity > object.item.quantity %}
            <td>Order quantity is higher than stock</td>
                {% else %}
                    {% if object.status == "Denied" %}
                    <td>Request already Denied</td>
                        {% else %}
                            {% if object.status == "Approved" %}
                                <td>Request already Approved</td>
                                {% else %}
                                <td><a href="{% url 'tma_app:approve_request' object.request_id %}">Click this to approve request</a></td>
                            {% endif %}
                    {% endif %}
            {% endif %}
            {% if object.status == "Denied"%}
                <td>Request already Denied</td>
                {% elif object.status == "Approved" %}
                    <td>Request already Approved</td>
                    {% else %}
                        <td><a href="{% url 'tma_app:deny_request' object.request_id %}">Click this to deny request</a></td>
            {% endif %}
        </tr>
    {% endfor %}
    </table>
{% endblock %}
</body>
</html>